apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    name: test-service
    app: test-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: test-app-pod
    app: test-app
