apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: test-app-pod
      app: test-app
  template:
    metadata:
      name: test-app-pod
      labels:
        name: test-app-pod
        app: test-app
    spec:
      containers:
      - name: test-app
        image: gcr.io/moonlit-pursuit-269718/test-app
        ports:
        - containerPort: 8080
